version: '3.4'

services:
  skinet.api:
    image: ${DOCKER_REGISTRY-}skinetapi
    build:
      context: .
      dockerfile: Skinet.API/Dockerfile
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
