version: '3.4'

services:
  skinet.api:
    image: ${DOCKER_REGISTRY-}skinetapi
    build:
      context: .
      dockerfile: Skinet.API/Dockerfile
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
  
volumes:
  redis-data:

